/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(probe_mer_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d38fbe0414f43dca5a22c590e0238e1b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <mer/probe_mer_c.h>
// pydoc.h is automatically generated in the build directory
#include <probe_mer_c_pydoc.h>

void bind_probe_mer_c(py::module& m)
{

    using probe_mer_c    = gr::mer::probe_mer_c;


    py::class_<probe_mer_c, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<probe_mer_c>>(m, "probe_mer_c", D(probe_mer_c))

        .def(py::init(&probe_mer_c::make),
           D(probe_mer_c,make)
        )
        



        ;




}








