/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qam_desrotator_cf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(16f379912bef90c683037aeabf311719)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <mer/qam_desrotator_cf.h>
// pydoc.h is automatically generated in the build directory
#include <qam_desrotator_cf_pydoc.h>

void bind_qam_desrotator_cf(py::module& m)
{

    using qam_desrotator_cf    = gr::mer::qam_desrotator_cf;


    py::class_<qam_desrotator_cf, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<qam_desrotator_cf>>(m, "qam_desrotator_cf", D(qam_desrotator_cf))

        .def(py::init(&qam_desrotator_cf::make),
           D(qam_desrotator_cf,make)
        )
        



        ;




}








